<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>Jade Ferreira</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">

    <link href="/open-iconic/font/css/open-iconic.css" rel="stylesheet">

    <link rel="stylesheet" href="/css/views/layout.css">

    <link rel="stylesheet" href="https://cdn.rawgit.com/konpa/devicon/df6431e323547add1b4cf45992913f15286456d3/devicon.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Times+New+Roman+OS">

    <!-- development version, includes helpful console warnings -->
    <script src="https://cdn.jsdelivr.net/npm/vue/dist/vue.js"></script>

    <!-- production version, optimized for size and speed (may specify version for robustness) -->
    <script src="https://cdn.jsdelivr.net/npm/vue"></script>
    <!--<script src="https://cdn.jsdelivr.net/npm/vue@2.6.11"></script>-->

    <link rel="icon" href="/img/logo-jf.png" type="image/gif" sizes="16x16">

    <!-- Scripts -->
    <?= $this->inlineScript()
        ->prependFile($this->basePath('js/bootstrap.min.js'))
        ->prependFile($this->basePath('js/jquery-3.3.1.min.js'))
    ?>

    <!-- PAGE STYLESHEET START -->
    <?php echo $this->placeholder('page-css') ?>
    <!-- PAGE STYLESHEET END -->

</head>
<body>

<div class="container">
    <?= $this->content ?>
</div>
<?= $this->inlineScript() ?>

<?= $this->placeholder('script-js'); ?>

</body>
</html>
