<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>Jade Ferreira | Engenheira de Software</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">

    <link href="/open-iconic/font/css/open-iconic.css" rel="stylesheet">

    <link rel="stylesheet" href="css/style.css">

    <link rel="stylesheet"
          href="https://cdn.rawgit.com/konpa/devicon/df6431e323547add1b4cf45992913f15286456d3/devicon.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="icon" href="/img/logo-jf.png" type="image/gif" sizes="16x16">

    <!-- Scripts -->
    <?= $this->inlineScript()
        ->prependFile($this->basePath('js/bootstrap.min.js'))
        ->prependFile($this->basePath('js/jquery-3.3.1.min.js'))
    ?>

    <?= $this->placeholder('page-css'); ?>

    <style>
        
    </style>
</head>


<body>


<!-- Container Zend -->
<div class="container">
    <?= $this->content ?>
    <!--hr>
    <footer>
        <p>&copy; 2005 - <?= date('Y') ?> by Zend Technologies Ltd. All rights reserved.</p>
    </footer-->
</div>
<?= $this->inlineScript() ?>
</body>
</html>
