<!-- CSS -->
<?php $this->placeholder('page-css')->captureStart(); ?>
<link rel="stylesheet" type="text/css" href="/css/views/home.css">
<link rel="stylesheet" type="text/css" href="/css/views/layout.css">
<link rel="stylesheet" type="text/css" href="/css/base/_variables.scss">
<link rel="stylesheet" type="text/css" href="/css/libraries/_mixins.scss">
<?php $this->placeholder('page-css')->captureEnd(); ?>


<div class="menu-bar" id="menu-bar">
    <a href="javascript:void(0);" class="icon" onclick="myFunction()"><i class="fa fa-bars"></i></a>
    <a href="https://www.linkedin.com/in/jadefr/"><i class="fa fa-linkedin" style="font-size:20px"
                                                     id="linkedin-icon"></i></a>
    <a href="https://github.com/jadefr/"> <i class="fa fa-github" style="font-size:20px"></i></a>
    <a href="#contato" class="font-third">Contato</a>
    <a href="#educação" class="font-third">Educação</a>
    <a href="#projetos" class="font-third" id="btn-projetos">Projetos</a>
    <a href="#destaques" class="font-third">Destaques</a>
</div>

<div class="header_logo-box">
    <img src="img/logo-jf.png" alt="jf" class="logo_image">
</div>

<!-- Header -->
<header class="header" id="#">
    <div class="header_text-box">
        <span class="font-first-main main-animated">Jade Ferreira</span>
        <span class="font-first-sub sub-animated">Engenheira de Software</span>
        <a href="#skills" class="btn btn-header btn-animated" id="btn-smooth">Mais</a>
    </div>
</header>

<main>

    <!-- Sobre Mim -->
    <section id="skills">
        <div class="skills_text-box">
            <span class="font-second-plain">Foco em</span>
            <span class="font-second-bold"> Back End</span>
            <br>
            <span class="font-second-plain">com experiência</span>
            <span class="font-second-bold"> Full Stack</span>
        </div>
        <hr>
        <div class="skills_icon-box">
            <div id="skills_icon-box-first">
                <i class="devicon-php-plain icon"></i>
                <i class="devicon-java-plain-wordmark icon"></i>
                <i class="devicon-javascript-plain icon"></i>
                <i class="devicon-vuejs-line-wordmark icon"></i>
            </div>
            <div id="skills_icon-box-second">
                <i class="devicon-html5-plain-wordmark icon"></i>
                <i class="devicon-css3-plain-wordmark icon"></i>
                <i class="devicon-sass-original icon"></i>
                <i class="devicon-bootstrap-plain icon"></i>
            </div>
        </div>
    </section>

    <!-- Destaques -->
    <section id="destaques">
        <div class="section-title">
            <span class="font-second-plain">Destaques</span>
            <hr>
        </div>
        <div class="destaques_item" id="distinctio">
            <div class="destaques_image_container" id="distinctio_image_container">
                <a href="https://github.com/jadefr/distinctio"><img src="/img/distinctio.png" class="image destaques_image"></a>
            </div>
            <div class="destaques_text_container" id="distinctio_text_container">
                <span class="font-third destaques_font-title">Distinctio</span>
                <p class="destaques_font-subtitle">Galeria de textos antigos responsiva e de UX agradável</p>
                <p>Vue.js/Vue Router/Vuex, BootstrapVue, Sass</p>
                <div class="destaques_buttons">
                    <a href="https://jadefr.github.io/distinctio/" class="btn btn-destaques btn-destaques-first">Projeto</a>
                    <a href="https://distinctio.jadeferreira.com.br/" class="btn btn-destaques btn-destaques-second">Ir para o site</a>
                </div>
            </div>
        </div>
        <hr class="between-items">
        <div class="destaques_item" id="aed">
            <div class="destaques_text_container" id="aed_text_container">
                <span class="font-third destaques_font-title">Estrutura de Dados</span>
                <p class="destaques_font-subtitle">Tabela hash de árvores</p>
                <p>Java</p>
                <div class="destaques_buttons">
                    <a href="https://jadefr.github.io/AED/" class="btn btn-destaques btn-destaques-first">Projeto</a>
                    <a href="https://github.com/jadefr/AED" class="btn btn-destaques btn-destaques-second">Código</a>
                </div>
            </div>
            <div class="destaques_image_container" id="aed_image_container">
                <a href="https://github.com/jadefr/AED"><img src="/img/tabela-hash4.png" class="image destaques_image"></a>
            </div>
        </div>
        <hr class="between-items">
        <div class="destaques_item" id="quiz">
            <div class="destaques_image_container" id="quiz_image_container">
                <a href="https://github.com/jadefr/quiz"><img src="/img/quiz.jpg" class="image destaques_image"></a>
            </div>
            <div class="destaques_text_container" id="quiz_text_container">
                <span class="font-third destaques_font-title">Quiz</span>
                <p class="destaques_font-subtitle">Jogo</p>
                <p>Vue.js, Lodash, CSS</p>
                <div class="destaques_buttons">
                    <a href="https://jadefr.github.io/quiz/" class="btn btn-destaques btn-destaques-first">Projeto</a>
                    <a href="https://quiz.jadeferreira.com.br/" class="btn btn-destaques btn-destaques-second">Ir para o site</a>
                </div>
            </div>
        </div>
    </section>

    <!-- Dark Bar -->
    <div class="dark-bar"></div>

    <!-- Projetos -->
    <section id="projetos">
        <div class="section-title">
            <span class="font-second-plain">Outros Projetos</span>
            <hr>
        </div>
        <ul>
            <li>
                <div class="card">
                    <a href="https://github.com/jadefr/semantic-iot/blob/master/README.md"><img src="/img/semantic-iot.PNG"
                                                                          class="image projetos_image"
                                                                          alt="semantic-iot"></a>
                    <div class="card-content">
                        <span class="font-third">Semantic IoT</span>
                        <p>PHP, JavaScript, CSS, HTML</p>
                        <a href="https://github.com/jadefr/semantic-iot" class="btn btn-projetos">Código</a>
                    </div>
                </div>
            </li>
            <li>
                <div class="card">
                    <a href="https://github.com/pgcc/e-seco/blob/master/README.md"><img src="img/eseco.png" class="image projetos_image"
                                                                  alt="eseco"></a>
                    <div class="card-content">
                        <span class="font-third">E-SECO</span>
                        <p>Java, Spring MVC, Hibernate</p>
                        <a href="https://github.com/pgcc/e-seco" class="btn btn-projetos">Código</a>
                    </div>
                </div>
            </li>
            <li>
                <div class="card">
                    <a href="https://github.com/jadefr/iot-data-retriever/blob/master/README.md"><img src="/img/iot-data-retriever.jpg"
                                                                                class="image projetos_image"
                                                                                alt="iot-data-retriever"></a>
                    <div class="card-content">
                        <span class="font-third">IoT Data Retriever</span>
                        <p>Java, RESTful API, Spring MVC</p>
                        <a href="https://github.com/jadefr/iot-data-retriever" class="btn btn-projetos">Código</a>
                    </div>
                </div>
            </li>
            <li>
                <div class="card">
                    <a href="https://github.com/jadefr/zend-test/blob/master/README.md"><img src="/img/crud.png"
                                                                       class="image projetos_image"
                                                                       alt="zend"></a>
                    <div class="card-content">
                        <span class="font-third">Cadastro de alunos</span>
                        <p>PHP, Zend Framework 3, SQL</p>
                        <a href="https://github.com/jadefr/zend-test" class="btn btn-projetos">Código</a>
                    </div>
                </div>
            </li>
            <li>
                <div class="card">
                    <a href="https://github.com/jadefr/angelus-bot/blob/master/README.md"><img src="/img/telegram.png"
                                                                         class="image projetos_image"
                                                                         alt="telegram"></a>
                    <div class="card-content">
                        <span class="font-third">Angelus Bot</span>
                        <p>Java, Telegram API</p>
                        <a href="https://github.com/jadefr/angelus-bot" class="btn btn-projetos">Código</a>
                    </div>
                </div>
            </li>
            <li>
                <div class="card">
                    <a href="https://github.com/jadefr/ontology-wcm/blob/master/README.md"><img src="/img/ontology.png" class="image projetos_image"
                                                                          alt="hash-table"></a>
                    <div class="card-content">
                        <span class="font-third">Ontologia</span>
                        <p>OWL</p>
                        <a href="https://github.com/jadefr/ontology-wcm" class="btn btn-projetos">Código</a>
                    </div>
                </div>
            </li>
            <li>
                <div class="card">
                    <a href="https://github.com/jadefr/linked-list/blob/master/README.md"><img src="/img/linked-list.png" class="image projetos_image"
                                                                          alt="linked-list"></a>
                    <div class="card-content">
                        <span class="font-third">Lista Encadeada</span>
                        <p>Java</p>
                        <a href="https://github.com/jadefr/linked-list" class="btn btn-projetos">Código</a>
                    </div>
                </div>
            </li>
            <li>
                <div class="card">
                    <a href="https://github.com/jadefr/queue/blob/master/README.md"><img src="/img/queue.png" class="image projetos_image"
                                                                         alt="queue"></a>
                    <div class="card-content">
                        <span class="font-third">Fila</span>
                        <p>Java</p>
                        <a href="https://github.com/jadefr/queue" class="btn btn-projetos">Código</a>
                    </div>
                </div>
            </li>
            <li>
                <div class="card">
                    <a href="https://github.com/jadefr/stack/blob/master/README.md"><img src="/img/stack.png" class="image projetos_image" id="stack-img"
                                                                                         alt="stack"></a>
                    <div class="card-content">
                        <span class="font-third">Pilha</span>
                        <p>Java</p>
                        <a href="https://github.com/jadefr/stack" class="btn btn-projetos">Código</a>
                    </div>
                </div>
            </li>
            <li>
                <div class="card">
                    <a href="https://github.com/jadefr/binary-search-tree/blob/master/README.md"><img src="/img/binary-search-tree.png" class="image projetos_image" id="binary-search-tree-img" alt="binary-search-tree"></a>
                    <div class="card-content">
                        <span class="font-third">Árvore Binária de Busca</span>
                        <p>Java</p>
                        <a href="https://github.com/jadefr/binary-search-tree" class="btn btn-projetos">Código</a>
                    </div>
                </div>
            </li>
        </ul>
    </section>

    <!-- Dark Bar -->
    <div class="dark-bar"></div>

    <!-- Educação -->
    <section id="educação">
        <div class="section-title">
            <span class="font-second-plain">Educação</span>
            <hr>
        </div>
        <ul>
            <li>
                <div class="card">
                    <a href="https://www.ufjf.br"><img src="/img/ufjf.jpg" class="educação_image" alt="ufjf"
                                                       id="ufjf"></a>
                    <div class="card-content">
                        <h3>Universidade Federal de Juiz de Fora</h3>
                        <p>Mestrado em Engenharia de Software</p>
                        <p>2017 - 2019</p>
                    </div>
                </div>
            </li>
            <li>
                <div class="card">
                    <a href="https://www.maynoothuniversity.ie/"><img src="/img/nuim.png" class="educação_image"
                                                                      alt="nuim"></a>
                    <div class="card-content">
                        <h3>National University of Ireland</h3>
                        <p>Engenharia Eletrônica (graduação sanduíche)</p>
                        <p>2013 - 2014</p>
                    </div>
                </div>
            </li>
            <li>
                <div class="card">
                    <a href="https://www.uff.br"><img src="/img/uff.png" class="educação_image" alt="uff" id="uff"></a>
                    <div class="card-content">
                        <h3>Universidade Federal Fluminense</h3>
                        <p>Engenharia de Telecomunicações</p>
                        <p>2010 - 2016</p>
                    </div>
                </div>
            </li>
        </ul>
    </section>
</main>
<footer>
    <div class="footer_container-first">
        <div class="footer_contact-box" id="contato">
            <div class="footer_contact-box-text">
                <h2 class="font-fourth-main">Contato</h2>
                <i class="fa fa-envelope footer_icon-first"></i>
                <p class="font-fourth-sub">jade@ice.ufjf.br</p>
                <br>
                <i class="fa fa-whatsapp footer_icon-first"></i>
                <p class="font-fourth-sub">+5521967855274</p>
            </div>
        </div>
        <div class="footer_logo-box">
            <a href=""><img src="img/logo-jf-white.png" alt="jf" class="logo_image" id="footer_logo-image"></a>
        </div>
        <div class="footer_quick-links">
            <div class="footer_quick-links-text">
                <h2 class="font-fourth-main">Quick Links</h2>
                <a href="#skills"><p class="font-fourth-sub" id="footer_skills">Skills</p></a><br>
                <a href="#projetos"><p class="font-fourth-sub" id="footer_projetos">Projetos</p></a><br>
                <a href="https://ieeexplore.ieee.org/abstract/document/8791911"><p class="font-fourth-sub">
                        Publicações</a></p>
            </div>
        </div>
    </div>
    <div class="footer_container-second">
        <div class="div_first">
        </div>
        <div class="footer_text-box">
            <p>Desenvolvido por <a href="https://github.com/jadefr/portfolio">Jade Ferreira</a></p>
        </div>
        <div class="footer_icon-box-second">
            <a href="https://www.linkedin.com/in/jadefr/"><i class="fa fa-linkedin footer_icon-second"></i></a>
            <a href="https://github.com/jadefr/"><i class="fa fa-github footer_icon-second"></i></a>
        </div>
    </div>
</footer>

<!-- JS -->
<?php $this->placeholder('script-js')->captureStart(); ?>
<script>
    /**
     *  Menu responsivo
     */
    function myFunction() {
        var x = document.getElementById("menu-bar");
        if (x.className === "menu-bar") {
            x.className += " responsive";
        } else {
            x.className = "menu-bar";
        }
    }
</script>
<?php $this->placeholder('script-js')->captureEnd(); ?>